config/routes.rb
Rails.application.routes.draw do
  root "homes#index"
  devise_for :admin_users, path: "admin"
  namespace :admin do
    root "homes#index"
    resources :notifications
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # :registerable, :recoverable, 
  devise :database_authenticatable, :rememberable, 
         :validatable, :trackable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/notification.rb
class Notification < ApplicationRecord
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  layout "admin/layouts/admin.html.erb"
  before_action :authenticate_admin_user!
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < Admin::AdminController
  def index
  end
end

app/controllers/admin/notifications_controller.rb
class Admin::NotificationsController < Admin::AdminController
  def show
    @notification = Notification.find(params[:id])
  end

  def new
    @notification = Notification.new
  end

  def create
    notification = Notification.create!(notification_params)
    redirect_to admin_notification_path(notification)
  end

  private

  def notification_params
    params.require(:notification).permit(:title, :content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @notifications = Notification.order(updated_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/homes/index.html.erb
<h1>管理者画面トップページ</h1>
<%= link_to "お知らせ新規投稿", new_admin_notification_path %>

app/views/admin/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviseAdminSample01</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "ログアウト", destroy_admin_user_session_path, method: :delete, data: {confirm: "ログアウトしますか？"} %>
    <hr>
    <%= yield %>
  </body>
</html>

app/views/admin/notifications/create.html.erb
<h1>Admin::Notifications#create</h1>
<p>Find me in app/views/admin/notifications/create.html.erb</p>

app/views/admin/notifications/new.html.erb
<h1>管理者画面お知らせ新規投稿</h1>
<!-- url の指定も必要 -->
<!-- Rails 6.1 以降なら「local: true」は不要 -->
<%= form_with model: @notification, url: admin_notifications_path, local: true do |form| %>
  <p>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :content %>
    <%= form.text_area :content %>
  </p>
  <p>
    <%= form.submit "送信" %>
  </p>
<% end %>

app/views/admin/notifications/show.html.erb
<p>タイトル: <%= @notification.title %></p>
<p><%= simple_format(h @notification.content) %></p>
<hr>
<p><%= link_to "お知らせ新規投稿", new_admin_notification_path %></p>

app/views/homes/_notification.html.erb
<p>タイトル: <%= notification.title %></p>
<p><%= simple_format(h notification.content) %></p>
<hr>

app/views/homes/index.html.erb
<h1>トップページ</h1>
<%= render partial: "homes/notification", collection: @notifications %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviseAdminSample01</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>